name: 'kubectl-simple-tailscale'
description: 'The kubectl command line program as a GitHub Action via Tailscale'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.config }}
    - ${{ inputs.command }}
    - ${{ inputs.tailscale_version }}
    - ${{ inputs.tailscale_key }}
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  version:
    description: 'kubectl version, e.g. `v1.21.0`, defaults to latest'
    required: false
    default: latest
  config:
    description: 'kube config data'
    required: true
  command:
    description: 'kubectl command to run, without the kubectl, e.g. `get pods`'
    required: true
  tailscale_version:
    description: 'Tailscale version to run'
    required: true
    default: 1.12.1
  tailscale_key:
    description: 'Tailscale ephemeral key'
    required: true
